### ISSUE TITLE
Reproductions for ATARI offline data

### ISSUE THREAD

**Issue by JayanthRR** [takuseno/d3rlpy#149]
Hi @takuseno ,

Do you have any reproductions on the offline ATARI data? There is a recent commit #46f48a9 for QR-DQN. Do you have the training logs for QR-DQN or DiscreteCQL? I observe that the MuJoCo gym reproductions are available at https://github.com/takuseno/d3rlpy-benchmarks. I would be very helpful if the ATARI baselines are also available. 

Thanks for the great work,
Jayanth.

**Comment by takuseno** [comment]
@JayanthRR Hello, thanks for the issue.

This is a very good question. Currently, I'm working on reproducing the result. Since my computational resources are limited, it takes time to make them available in public. But, I'm sure that the reproduction code is correct. `discrete_cql.py` code is not up-to-date, but I can quickly commit it to align with `qr_dqn.py` if necessary.

**Comment by takuseno** [comment]
The latest reproduction script for DiscreteCQL is available here.
https://github.com/takuseno/d3rlpy/blob/master/reproductions/offline/discrete_cql.py

I confirmed it performs  as well as the result reported in the paper.

**Comment by JayanthRR** [comment]
Thank you so much.
