### ISSUE TITLE
[REQUEST] Offline Reproduction of AWR

### ISSUE THREAD

**Issue by im-Kitsch** [takuseno/d3rlpy#154]
Hello,

thanks a lot for your work. I wanna to reproduce the result of AWR, however, it seems there is no implementation in ./reproductions/offlines/ folder. Would you like to add reproduce of AWR algorithm?

Thanks a lot

**Comment by takuseno** [comment]
Hello, thanks for the issue. Unfortunately, AWR reproduction is not planned and AWR will be dropped in the future because it has a slightly different training scheme and is less powerful than the other methods. Most importantly, AWR is not really used in recent papers.  Sorry about the inconvenience.

**Comment by takuseno** [comment]
Let me close this issue for now.
