### ISSUE TITLE
Dataset of d4rl

### ISSUE THREAD

**Issue by im-Kitsch** [takuseno/d3rlpy#164]
Hi,

It's nice to use your implementation of dataset. 

But I find that the observation repeated at the end. E.g. you can just run 

> env = gym.make('hopper-medium-v0‘）
dataset  = d4rl.qlearning_dataset(env)
d3rl_data, _ = d3rlpy.datasets.get_dataset('hopper-medium-v0')

The first trajectory finished at step 211. You can compare, 
 `dataset['next_observations'][210]， dataset['observations'][211]， d3rl_data.episodes[0].transitions[210].observation， d3rl_data.episodes[0].transitions[209].next_observation`. 

Looks the next transiiton of the last transition just repeated. But the observation should be different, it would make some problem for some algorithms. 

thanks for your contribuiton.

Best

**Comment by takuseno** [comment]
@im-Kitsch Hi, thanks for the issue.

I don't actually understand the problem here. `d3rl_data.episodes[0].transitions[210].observation` must be identical to `d3rl_data.episodes[0].transitions[209].next_observation` because the current observation should the next observation at the last step.

**Comment by im-Kitsch** [comment]
Hi, @takuseno ,

Sorry I typed the index not so exactly since hurry. I guess you can just choose one dataset, e.g. ‘hopper-medium-v0’, you can check the last transition of first episode, compare it’s `observation` and the `next_observation`. The observations are the same, while it should be different. Also it’s truely different in d4rl’s dataset, it could be easily validated as derlei.qlearning_dataset. 

Best.

**Comment by takuseno** [comment]
@im-Kitsch Hi, I guess you're using `v1.0.0`. The last repeated observation is intentional.
https://github.com/takuseno/d3rlpy/blob/8eb11db2d6f406cfab6d08adc4e0c08666dd063e/d3rlpy/datasets.py#L344

When the terminal flag is on, it does not matter what `next_observation` is because the target value will be multiplied by 0 anyway. Also, in the latest master branch, such states will be zeros.
https://github.com/takuseno/d3rlpy/blob/500b5e1ef96887a6f42b3b4c60f247c1152e1689/d3rlpy/dataset.pyx#L89

Please use it as is since it's not a bug.

**Comment by im-Kitsch** [comment]
Hi, 

sorry for the late reply? 

although last step of dataset is rarely used. However, is there any reason that repeat the last observation or use the last observation as zero?  Since I think keep the original observation should be better.

Personlly I focus mostly on mujoco environment. Acutally d4rl has new version of dataset, e.g. xxx-xxxx-v2, you can get the next_obervation of last timestip. 

I understand that you design of this feature. But would it be better to use the orignial next observation rather than repeat or set as zero?

Best

**Comment by takuseno** [comment]
The next observation in d4rl is not really the `true` next observation.
https://github.com/rail-berkeley/d4rl/blob/4aff6f8c46f62f9a57f79caa9287efefa45b6688/d4rl/__init__.py#L105

At the terminal state, this will be the first observation of the next episode. There is no reason to follow this in d3rlpy.

**Comment by im-Kitsch** [comment]
Hi, @takuseno , 

thanks for the quick reply. I think d4rl `qlearning_dataset()` is problematic. 

On the one hand, d3rlpy uses `env.get_dataset()` rather than `qlearning_dataet()`. In original dataset, the `next_observations` is normal and doesn't use the 1st obs of next episode. 

On the other hand, `qlearning_dataset()` mostly drop the last timestamp's transition due to default setting `terminate_on_end=False`. 

I opened  a new ticket on d4rl. Maybe you can check this.

https://github.com/rail-berkeley/d4rl/issues/145#issue-1145732463

Best.

**Comment by takuseno** [comment]
There is no `next_observation` data in the original dataset. I think setting zeros might be the best way to express the terminal states since it's very explicit. Also, `terminate_on_end` is used to drop the timeout state because there is no way to use such a state since we need a true `next_observation` for it, which does not exist in the dataset.

**Comment by takuseno** [comment]
I just found that `v1` datasets have `next_observations`, which don't exist in `v0` datasets. However, for the backward compatibility, I don't think d3rlpy will use `next_observations` for now.
