### ISSUE TITLE
results on AntMaze or Adroit

### ISSUE THREAD

**Issue by cclvr** [takuseno/d3rlpy#203]
Hi @takuseno,
   Thanks for your excellent codebase and it helps me a lot.  
   I have a question that, do you conduct experiments on AntMaze or Adroit tasks？ I have tried DiscreteCQL on AntMaze, but the results are not compatible with those reported in CQL paper. So may I have some of your suggestions on these tasks, such as the hyperparameter setting or some other points?
   Thanks a lot in advance~

**Comment by takuseno** [comment]
@cclvr Hi, as far as I know, AntMaze and Adroit are continuous control tasks. Why did you use `DiscreteCQL` instead of `CQL`? Personally, I have not tried them yet, but I know there is parameter difference between MuJoCo experiments and those tasks according to the paper. You can modify `reproduction/offline/cql.py` to match the parameters and try it out.

**Comment by cclvr** [comment]
> @cclvr Hi, as far as I know, AntMaze and Adroit are continuous control tasks. Why did you use `DiscreteCQL` instead of `CQL`? Personally, I have not tried them yet, but I know there is parameter difference between MuJoCo experiments and those tasks according to the paper. You can modify `reproduction/offline/cql.py` to match the parameters and try it out.

Yes, you are right, I made some confusion, sorry for taking your time and thanks.

**Comment by takuseno** [comment]
sounds like the issue has gone. let me close this.
