### ISSUE TITLE
[Question] Which function is equivalent to `d4rl.qlearning_dataset`?

### ISSUE THREAD

**Issue by Mamba413** [takuseno/d3rlpy#208]
`d4rl.qlearning_dataset` is a standard function for offline RL research. I wonder how can I (approximately) reproduce the dataset returned by `d4rl.qlearning_dataset`.

**Comment by takuseno** [comment]
I removed bug label since this is not definitely a bug. Regarding `d4rl.qlearning_dataset`, it's internally done during the training. Please see more details in the [documentation](https://d3rlpy.readthedocs.io/en/v1.1.1/tutorials/play_with_mdp_dataset.html).

**Comment by Mamba413** [comment]
Does you mean `d3rlpy`  use `d4rl.qlearning_dataset` internally? For example, when I use function `d3rlpy.online.buffers.ReplayBuffer`,  `d4rl.qlearning_dataset` is called?

**Comment by takuseno** [comment]
`d4rl.qlearning_dataset` is never used in d3rlpy. For example.
```py
import d3rlpy
dataset, env = d3rlpy.datasets.get_dataset("hopper-random-v0")
```
`dataset` is  `MDPDataset` object, which internally splits into `Transition` objects that have the exactly same as the tuple used in Q-learning. Please check the documentation above.

**Comment by takuseno** [comment]
Basically, as long as you use d3rlpy, you don't need to think about the details of how the dataset is treated otherwise there is no reason to use this sort of library. If you want to use your own datasets, please check related tutorials:
- https://d3rlpy.readthedocs.io/en/v1.1.1/tutorials/create_your_dataset.html
- https://d3rlpy.readthedocs.io/en/v1.1.1/tutorials/data_collection.html

**Comment by Mamba413** [comment]
Thanks for your excellent response！
