### ISSUE TITLE
Question: are RNN-style network architectures supported?

### ISSUE THREAD

**Issue by jaak-s** [takuseno/d3rlpy#214]
I was looking into custom network architectures and saw that the module class examples have signature `forward(self, x)`.
I'd be interested to use RNN-style network, i.e., `forward(self, x, h=None)` where `h` is the previous hidden state and the `forward` function should also then return the next hidden state, passing the gradients through the RNN hidden state during back-prop.

Is this possible? Thanks!

BTW You have created a very nice library!

**Comment by takuseno** [comment]
@jaak-s Hi, thanks for the issue! Currently, RNN architectures are not supported mainly because of dataset sampling logics. I'm currently working on refactoring this to support Transformer architectures (e.g. Decision Transformer). Once we get this in master, RNN could be also supported. Please check this branch for the progress.
https://github.com/takuseno/d3rlpy/tree/dataset_refactoring

**Comment by jaak-s** [comment]
@takuseno Hi, brilliant, thanks!
