### ISSUE TITLE
[REQUEST] Support Gymnasium

### ISSUE THREAD

**Issue by jwarley** [takuseno/d3rlpy#239]
[Gymnasium](https://github.com/Farama-Foundation/Gymnasium) is the official [successor](https://farama.org/Announcing-The-Farama-Foundation) of OpenAI Gym.

The API is backward-compatible with gym, but gymnasium environments don't currently work with d3rlpy because of several places where d3rlpy relies explicitly on gym types ([example](https://github.com/takuseno/d3rlpy/blob/4c2691f6f1219a182b50849180ea285504f7d352/d3rlpy/online/utility.py#L8)).

Supporting gymnasium is equivalent to supporting gym v0.26.2 and replacing gym by gymnasium in any imports.

**Comment by asmith26** [comment]
I'm also interested in this.

I'm happy to have a go at this if helpful - I'm quite new to this lib, but I'm loving it so would be keen to help in anyway.
Any help is greatly appreciated regarding where the required updates that need to be undertaken (possibly a good place to start: https://github.com/takuseno/d3rlpy/blob/master/tests/envs/test_wrappers.py)

**Comment by takuseno** [comment]
@asmith26 Hi, Gymnasium is already supported in the latest master since this [commit](https://github.com/takuseno/d3rlpy/commit/94d03d55baa2953f28ac6c32269ee7c71f06a823). You can see an example [here](https://github.com/takuseno/d3rlpy/blob/master/examples/gymnasium_env.py). This commit will be included in the next release. If you want to use this feature now, you can can install d3rlpy from source:
```
$ git clone https://github.com/takuseno/d3rlpy
$ cd d3rlpy
$ pip install -e .
```

**Comment by takuseno** [comment]
Since this is already supported, let me close this issue :smile:
