### ISSUE TITLE
 How can I accelerate my training [HELP]

### ISSUE THREAD

**Issue by 8JasonStatham8** [takuseno/d3rlpy#263]
I create my own MDPDataset .
It just have 19780 episodes, I use asizeof() in pympler to compute the size of my data, it's 338MB.
My GPU is TITAN Xp , and I have 4 GPUs.
When I use DiscreteCQL to training, I find it just running on the GPU:0 ,and  Volatile GPU-Util is just 12% . The GPU:1,2,3 is free. 
When I set the batch_size is 8 or 16 or 32 , each epoch will spend 6 minuate. But when I up the batch_size to 1024 , each epoch will spend more long time, I can't understand Why.
I think the performance is too waste.
So I want to accelerate  my training.
Do you have some suggestion?
Thanks.

**Comment by takuseno** [comment]
@8JasonStatham8 Hi, thank you for using d3rlpy. When increasing the batch size, the computational cost also grows. So, it sounds sane to me. Also, if the observation dimension is small, you can't maximize GPU utility either.

**Comment by 8JasonStatham8** [comment]
> 

But when I set batch_size to 1024, that my Volatile GPU-Util is just 16%. It 's not grow very high, I think it may be not the reason .

**Comment by mindacrobatic** [comment]
@takuseno @8JasonStatham8 

Maybe we should not open this issue yet, because I am running also into issues with GPU acceleration.

I was running CQL in an AWS Sagemaker notebook with GPU (ml.p3.8xlarge). I observed that using cuda did not speed up training, it actually made it slower (d3rlpy version 2.0.4)

Let me give you some details:
I have this code:

```
batch_size = 512
device = "cpu"

cql = DiscreteCQLConfig(
    learning_rate=learning_rate,
    target_update_interval=target_update_interval,
    batch_size=batch_size
).create(device=device)

n_steps_per_epoch = 3000
epochs = 300000

cql.fit(
    dataset,
    evaluators={
        'td_error': TDErrorEvaluator(episodes=test_episodes),
        'average_value': AverageValueEstimationEvaluator(test_episodes),
        'initial_state_value': InitialStateValueEstimationEvaluator(test_episodes) 
    },
    n_steps=epochs*n_steps_per_epoch,
    n_steps_per_epoch=n_steps_per_epoch,
    save_interval=300000,
    show_progress=True
)
```

I varied batch_size (32, 256, 512) and device (cuda:0, cuda:1, cuda:2, cuda:3, cuda, cpu).

This is what I get in terms of iterations per second: 

**Batch=32**
Cuda:0 —> 143it/s
Cuda:1 —> 143it/s
Cuda:2 —> 143it/s
Cuda:3 —> 143it/s
Cuda:4 —> error
Cuda —> 143it/s
cpu —> 182

**Batch=256**
Cuda —> 100it/s
Cpu —> 100it/s

**Batch=512**
Cuda —> 69it/s
Cpu —> 69it/s

You can see that CPU was at least on par with GPU, in case of a small batch size it even seemed faster. 

This is actually in line with the other issue that I had created for Mac M1 (https://github.com/takuseno/d3rlpy/issues/293). Here I tried the nightly branch on my Mac and did just like you said, but again training was slower with GPU use.

**Comment by takuseno** [comment]
@mindacrobatic I confirmed that `d3rlpy==2.0.4` correctly uses GPU for `DiscreteCQL` training. Here is my test code: 

```py
import d3rlpy

dataset, env = d3rlpy.datasets.get_atari("breakout-medium-v0", num_stack=4)

cql = d3rlpy.algos.DiscreteCQLConfig(
    learning_rate=5e-5,
    optim_factory=d3rlpy.models.optimizers.AdamFactory(eps=1e-2 / 32),
    batch_size=32,
    alpha=4.0,
    q_func_factory=d3rlpy.models.q_functions.QRQFunctionFactory(
        n_quantiles=200
    ),
    observation_scaler=d3rlpy.preprocessing.PixelObservationScaler(),
    target_update_interval=2000,
    reward_scaler=d3rlpy.preprocessing.ClipRewardScaler(-1.0, 1.0),
).create(device="cuda:0")

cql.fit(dataset, n_steps=10000, n_steps_per_epoch=1000)
```

Here is training speed with and without GPU (RTX4070)
- GPU: 145 iterations / sec (40% GPU utilization)
- CPU: 24 iterations /sec

Note that if I train `DiscreteCQL` with a toy task such as CartPole (with MLP layers with 256 units each), the one with CPU is actually faster than the one with GPU. This is because if the model is too small, data transfer between CPU and GPU becomes the bottleneck.

**Comment by takuseno** [comment]
Since this is not a d3rlpy issue, I suspect that your machine has a general GPU issue. For example, CPU Memory is outdated and slow to transfer data. The bandwidth between CPU and GPU is too low, etc.
