### ISSUE TITLE
[Question] - Increasing model capacity

### ISSUE THREAD

**Issue by paulhilders** [takuseno/d3rlpy#277]
Hi!

I am currently training a DiscreteCQL algorithm for a complicated task, and it seems the model is **underfitting** during training. Therefore, I want to increase the model capacity (i.e., increase the number of parameters). Can I use a VectorEncoderFactory for this? Or is there a better option to increase the model capacity during training?

I have tried using the VectorEncoderFactory with increasing sizes for the hidden units, ranging from [256, 256] to [1024,1024,512,256,256] and even [2048,2048,1024,1024,512,512,256,256], but this does not seem to make a lot of difference.

Additionally, I am wondering how the use of an encoder translates to the continuous CQL algorithm, where there is a separate actor_encoder_factory and critic_encoder_factory argument. Should I just use the same encoder factory for both of these?

Thank you in advance!

**Comment by takuseno** [comment]
Yes, `VectorEncoderFactory` is the right choice to change neural network models. Regarding the continuous CQL architecture, people usually use the same architecture for both actor and critic. Since learning Q-functions is the hardest problem in RL, you might choose the larger architecture for critic as well.

**Comment by paulhilders** [comment]
Great! Thank you for your quick response.
