### ISSUE TITLE
[BUG] Major: MDPDataset.load() has stopped working in the latest version

### ISSUE THREAD

**Issue by HassamSheikh** [takuseno/d3rlpy#312]
In version 2.x, `MDPDataset.load(file.h5)` is giving TypeError: load() missing 1 required positional argument: 'buffer'

**Comment by takuseno** [comment]
@HassamSheikh Thanks for the issue. It's not a bug. In v2, `MDPDataset` is completely different from the one in v1. Please check this documentation.
https://d3rlpy.readthedocs.io/en/v2.0.4/references/dataset.html

Because of this, the saved dataset in v1 is no longer compatible with v2. To load v1 dataset in v2, you can use this method.
https://github.com/takuseno/d3rlpy/blob/c05c3cfee7d0d0e9811132928aa4287199abc5c3/d3rlpy/dataset/io.py#L81

**Comment by HassamSheikh** [comment]
Thank you.

**Comment by ajam74001** [comment]
Hello, 
I loaded the data through load_v1 function without any problem. However, I am getting the following error while fitting it to CQL model.
ataset_info = DatasetInfo.from_episodes(dataset.episodes)
AttributeError: 'list' object has no attribute 'episodes'

**Comment by takuseno** [comment]
Yes, this is because `load_v1` returns a sequence of episodes, not `ReplayBuffer`. So you need to do as follows:
```py
import d3rlpy

episodes = d3rlpy.dataset.load_v1("xxx.h5")
buffer = d3rlpy.dataset.create_infinite_replay_buffer(episodes)
cql = d3rlpy.algos.CQLConfig().create()
cql.fit(buffer, n_steps=100000)
```
