### ISSUE TITLE
[Question] Why were some offline DRL algorithms removed, like MOPO, and COMBO?

### ISSUE THREAD

**Issue by Zed-Wu** [takuseno/d3rlpy#324]
I found that some algorithms (e.g., MOPO and COMBO) were deleted, What is the reason? Is it because their implementation has a bug?

**Comment by takuseno** [comment]
@Zed-Wu Hi, thank you for the issue. The reason was to keep implementation simple. Through the recent major update, it was difficult to maintain model-based algorithms. If you still want to use them, you can always use v1 packages. In the future release, I'm planning to get them back in a cleaner way.

**Comment by Zed-Wu** [comment]
Ok, thank you very much for your great support and maintenance of this project.

**Comment by knightnemo** [comment]
Hi, thank you for your great work. Up til now, MOPO and COMBO have still not been brought back. Do you have any plans of bringing it back in the future? I am currently using v1 branch of the repo, so it's absolutely fine it we decide not to bring it back. But also, are there some things(e.g. common pitfalls) that I should be aware of on the v1 version of repo? Thanks!
