### ISSUE TITLE
Any reason about depcrecating cython

### ISSUE THREAD

**Issue by im-Kitsch** [takuseno/d3rlpy#350]
Hi, 

I am curious why cython dependency is removed. I remembered that in 'v1' verstion there is fancy implementation of dataset structure. Especially for sharing memory things.  And I am planning to implenment similar structure. But looks it's deprecated in v2, is there any reason about derpecating? maybe performance limitation or cython problem?

Thanks

**Comment by takuseno** [comment]
@im-Kitsch Hi, thanks for the issue. The reason why I switched from Cython to full Pythonic implemenation was to provide flexibility to users. Previously, logics underlying `MDPDataset` cannot be modified because those components need to be compiled when the package is released. To support various use cases, I decided to change the design.

**Comment by im-Kitsch** [comment]
thanks for the reply
